### PR TITLE
Update chap01.md

### PR DESCRIPTION
**Pull request by Hugh-Zhu**
I've scanned the book and read the 'Introduction" carefully. And I've taken some alternatives in some statements to make it smoother for reading.
Forgive for my crude.

### CODE REVIEW

**Comment by billie66** [comment]
good work, thanks!

**Comment by Hugh-Zhu** [comment]
I am not major at computer related science and facing to graduation
pressure as a senior postgraduate, but I really fell in love with
Ubuntu and Linux when I am happened to do some bioinformatic analysis
with a lenovo server bought by my mentor.
I won't be confident for Linux to be popular until I read this book. I
think all the efforts you've spent on translating this book will
promote the ability for general persons to, as the author says,
"really control" the computer. So am I welcomed to contribute to it as
my time allows?

best,
2013.11.30

2013/11/30, Billie Zhang notifications@github.com:

**Comment by billie66** [comment]
The TLCL is an open source project, which is supported by the team from haoqicat.com, and we are really appreciated you for contributing your work. Up to now, TLCL still has several chapters not translated to Chinese. In order to finish this project, we hope you could translate those remained chapters in your free time.

**Comment by Hugh-Zhu** [comment]
I‘m glad so, just try my best in my free time.

2013/12/1 Billie Zhang notifications@github.com

**Pull request merged**
